repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Ty type checker - disabled for now as it's in beta
  # - repo: local
  #   hooks:
  #     - id: ty-check
  #       name: Ty type checker
  #       entry: pixi run ty-check
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true