# Baba Is AGI Configuration

[game]
# Path to your Baba Is You installation
path = "/Users/femtomc/Library/Application Support/Steam/steamapps/common/Baba Is You"

[mcp]
port = 5173
host = "localhost"

[agent]
max_turns = 50
default_level = "1"
verbose = true