[project]
name = "baba-is-agi"
version = "0.1.0"
description = "Autonomous agent that plays Baba Is You using Claude Code SDK and MCP"
authors = ["femtomc"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = ">=3.11,<3.13"
pip = "*"

[pypi-dependencies]
claude-code-sdk = "*"
mcp = "*"
pydantic = "*"
fastmcp = "*"
configparser = "*"
pyyaml = "*"
pyautogui = "*"
pillow = "*"
psutil = "*"
toml = "*"

[tasks]
play = "python scripts/play_game.py"
setup = "python scripts/setup_game.py"
test-mcp = "cd agent && python test_connection.py"