[project]
name = "baba-agent"
version = "0.1.0"
description = "Agent for playing Baba Is You using MCP server"
authors = ["Baba Agent"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = ">=3.11,<3.13"
pip = "*"

[pypi-dependencies]
claude-code-sdk = "*"
mcp = "*"
pydantic = "*"
fastmcp = "*"
configparser = "*"
pyyaml = "*"

[tasks]
run = { cmd = "python baba_agent.py" }